# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: '^.*\.py$'
repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: black --check --diff --color
      language: python
    - id: flake8
      name: flake8
      entry: flake8
      language: python
